- hosts: all
  vars:
    mysql_root_pass: vagrant

  tasks:

  - name: Install common packages
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - build-essential
      - ruby-dev
      - libsqlite3-dev
      - jq
      - curl
      - python-mysqldb

  # Apache2
  - name: Ensure apache is installed
    become: yes
    apt: pkg=apache2 state=latest
  - name: Activate mod rewrite
    become: yes
    apache2_module: state=present name=rewrite
  - name: Activate mod ssl
    become: yes
    apache2_module: state=present name=ssl
  - name: Make sure apache is running
    become: yes
    action: service name=apache2 state=started enabled=true

  # MySQL
  - name: Set MySQL root password before installing
    become: yes
    debconf:
      name: mysql-server
      question: mysql-server/root_password
      value: "{{mysql_root_pass | quote}}"
      vtype: password
  - name: Confirm MySQL root password before installing
    become: yes
    debconf:
      name: mysql-server
      question: mysql-server/root_password_again
      value: "{{mysql_root_pass | quote}}"
      vtype: password
  - name: Install MySQL
    become: yes
    apt: pkg=mysql-server state=latest
  - name: Make sure MySQL is running
    become: yes
    action: service name=mysql state=started enabled=true

  # PHP
  - name: Install PHP packages
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - php
      - libapache2-mod-php
      - php-cli
      - php-dev
      - php-mbstring
      - php-mcrypt
      - php-mysql
      - php-gd
      - php-curl
      - php-xdebug
      - composer
    notify: restart-apache

  # Ruby
  - name: Install Ruby
    become: yes
    apt: pkg=ruby state=latest

  # Node.js
  - name: Download Node.js PPM
    become: yes
    get_url:
      url: https://deb.nodesource.com/setup_6.x
      dest: /tmp/setup.sh
      mode: 0440
  - name: Install Node.js PPM
    become: yes
    shell: bash /tmp/setup.sh
  - name: Install Node.js
    become: yes
    apt: name=nodejs state=latest

  # RubyGems
  - name: Install Ruby gems
    gem:
      name: "{{ item }}"
      state: latest
      user_install: yes
    with_items:
      - bundler

  handlers:
    - name: restart-apache
      become: yes
      action: service name=apache2 state=restarted
    - name: restart-mysql
      become: yes
      action: service name=mysql state=restarted
